source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'bootstrap-sass', '~> 2.3.2.0'
# for has_secure_password
gem 'bcrypt-ruby', '~> 3.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# masa activated the below
gem 'therubyracer', platforms: :ruby

gem 'jquery-rails'
gem 'json', '1.8.2'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

group :doc do
  gem 'sdoc', require: false
end

group :development do
  gem 'quiet_assets'
  gem 'pry'
  #gem 'sqlite3', '1.3.11'
  gem 'pry-byebug'
end

gem 'sqlite3', '1.3.11'

gem 'capistrano', '~> 3.1.0'
gem 'capistrano-bundler', '~> 1.1.2'
# gem 'capistrano-rails', '~> 1.1.1'
gem 'capistrano-rails', '~> 1.1.3'

# Add this if you're using rbenv
gem 'capistrano-rbenv', github: "capistrano/rbenv"

# Add this if you're using rvm
# gem 'capistrano-rvm', github: "capistrano/rvm"

#group :production do
#  gem 'pg'
#  gem 'rails_12factor'
#end
